name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - name: Pull code
      run: git pull origin master
      working-directory: /opt/cms_leads
    - name: Directory Permissions
      run: chmod -R 777 storage
      working-directory: /opt/cms_leads
    - name: Install Node
      run: npm install
      working-directory: /opt/cms_leads/resources/coreui
    - name: Build Node
      run: npm run build
      working-directory: /opt/cms_leads/resources/coreui
    - name: Complete
      run: npm run watch &
      working-directory: /opt/cms_leads
