name: CMS_LEAD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cms_lead_production:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Pull
      run: git pull origin master
      working-directory: /var/www/lead_cms
    - name: Complete
      run: npm run dev
      working-directory: /var/www/lead_cms
